### ISSUE TITLE
Can you fix line 30? It highlights it and I think something is wrong with it. I am really bad at coding but I was wondering what was wrong with it. Thanks -GimkitHacker

### ISSUE THREAD

**Issue by GimkitHacker** [UndercoverGoose/classroom-cheats#13]

**Comment by ThatFruedDued** [comment]
@UndercoverGoose and I are currently in the process of fixing the script. Although your developer tools may supply line 30 as the issue, there is code on other lines more complex and not just a "simple fix". We also were pondering release when Gimkit changed the API on us, so you may have to wait a bit for the new script (if we do release it).

**Comment by muselkbeam** [comment]
@ThatFruedDued Is there a way I can help -- I've got some JS knowledge and might be able to contribute

**Comment by ThatFruedDued** [comment]
@muselkbeam sorry, we've made the hard decision to keep the script private. The chances of Gimkit patching this are simply too high. Even with obfuscation, Gimkit has many employees and would be able to decode our code. Even if they couldn't get through obfuscation, they would simply make small changes in their system until our script breaks. We probably will release this to a handful of private testers, but nothing is guaranteed yet.

**Comment by HoboManHobo** [comment]
Can you maybe remind us when the hack is fixed, that would be helpful.

**Comment by ThatFruedDued** [comment]
@HoboManHobo please read the above comment, this script will not work in the future.

**Comment by Hacks-lol** [comment]
come on we need it

**Comment by ThatFruedDued** [comment]
@Hacks-lol if you would like to purchase the script, you can contact me (`okr765#0702`) or @UndercoverGoose (`h c k r#8759`) on Discord to negotiate pricing. We are charging for the script so it has less publicity and less of a chance to get patched, and so we will not disappoint our previous buyers for making something freely available that they paid for.
