### ISSUE TITLE
cant read "length"

### ISSUE THREAD

**Issue by Thundersm** [UndercoverGoose/classroom-cheats#17]
Im really new to javascript so I have no idea what is wrong here but whenever I try to use the code it comes up with an error saying "cant read "length" of undefined" I dont know how to code so I dont have any idea how to fix this.

**Comment by A-Yamout** [comment]
@UndercoverGoose

**Comment by ThatFruedDued** [comment]
The script no longer works, sorry.

**Comment by A-Yamout** [comment]
@ThatFruedDued ok thanks
