### ISSUE TITLE
Gimkit API not working

### ISSUE THREAD

**Issue by sarthaktexas** [UndercoverGoose/classroom-cheats#4]
`GET https://www.gimkit.com/api/games/fetch/undefined 500 (Internal Server Error)`

It was working a few days ago, however now it just highlights the question.

**Comment by UndercoverGoose** [comment]
Updating the gimkit script! Hopefully it now works.

**Comment by UndercoverGoose** [comment]
Seems as though the new method MAY work in SOME kits because it creates the kit ID from the question IDs, and some kits have pretty random question IDs, so until further notice, it probably will not work.

**Comment by UndercoverGoose** [comment]
Script is patched, sorry!
