### ISSUE TITLE
It just does not work

### ISSUE THREAD

**Issue by DerpyBillGates** [UndercoverGoose/classroom-cheats#6]
the little menu button comes up but nothing inside of it works

**Comment by UndercoverGoose** [comment]
Gimkit has remove the kit ID from the JSON object which broke the script. I am currently working on a fix.

**Comment by Knocker379** [comment]
When can you have it done? I mean no rush, but I  need to use it within the next few days. Thanks for your hard work!

**Comment by UndercoverGoose** [comment]
Script is patched, sorry!
