### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by unluckydrop** [UndercoverGoose/classroom-cheats#9]
I'm not the best at understanding this so can I get a little more specific explanation on how to install it?

**Comment by Frostyanimations126** [comment]
create a bookmark and put ` javascript:(function(){let l=document.createElement("script");l.src="https://undercovergoose.github.io/quizlet/gimkit/gimkit.js";document.body.appendChild(l);}());void 0 ` in the url. Then click the bookmark when you are in gimkit
